import sqlite3
import os
from config import Config


def get_connection() -> sqlite3.Connection:
    """Return a SQLite connection with row_factory set to dict-like rows."""
    os.makedirs(os.path.dirname(Config.DB_PATH), exist_ok=True)
    conn = sqlite3.connect(Config.DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def init_db() -> None:
    """Create all tables (idempotent) and migrate older databases in place."""
    with get_connection() as conn:
        conn.executescript(_SCHEMA)
        _migrate(conn)


def _migrate(conn: sqlite3.Connection) -> None:
    """
    Add columns that didn't exist in earlier versions of the schema.
    SQLite has no "ADD COLUMN IF NOT EXISTS", so we check pragma_table_info
    first. Safe to run on every startup.
    """
    columns = {row["name"] for row in conn.execute("PRAGMA table_info(projects)")}
    if "owner_username" not in columns:
        # NULL owner = "legacy" project created before ownership existed.
        # PermissionModel treats these as owned by nobody in particular,
        # so any authenticated user keeps the access they had before.
        conn.execute("ALTER TABLE projects ADD COLUMN owner_username TEXT")
        conn.commit()


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------
# Design note: modules are intentionally schema-light.
# `data` is a JSON blob — each module type owns its own structure.
# `module_type` is the only coupling point; adding a new module type
# never requires a schema change.
#
# Permission model: a project has one owner (full access, implicit) and any
# number of members. Members are granted access via roles, which are defined
# per-project and carry a JSON array of permission strings (see
# models/permissions.py for the permission constants and enforcement).
# ---------------------------------------------------------------------------
_SCHEMA = """
CREATE TABLE IF NOT EXISTS projects (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    name           TEXT    NOT NULL,
    description    TEXT    DEFAULT '',
    color          TEXT    DEFAULT '#6366f1',
    owner_username TEXT,
    created_at     TEXT    DEFAULT (datetime('now')),
    updated_at     TEXT    DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS modules (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id  INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    module_type TEXT    NOT NULL,   -- e.g. 'notes', 'roadmap', 'mindmap', 'images'
    title       TEXT    NOT NULL,
    data        TEXT    DEFAULT '{}',  -- JSON blob owned by the module type
    position    INTEGER DEFAULT 0,     -- ordering within a project
    created_at  TEXT    DEFAULT (datetime('now')),
    updated_at  TEXT    DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_modules_project ON modules(project_id);

-- A role is a named bundle of permissions, scoped to one project.
CREATE TABLE IF NOT EXISTS roles (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id  INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name        TEXT    NOT NULL,
    permissions TEXT    NOT NULL DEFAULT '[]',  -- JSON array of permission strings
    created_at  TEXT    DEFAULT (datetime('now')),
    UNIQUE(project_id, name)
);

-- A member is a user who has been given access to a project (the owner is
-- implicit and does NOT need a row here).
CREATE TABLE IF NOT EXISTS project_members (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id  INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    username    TEXT    NOT NULL,
    added_at    TEXT    DEFAULT (datetime('now')),
    UNIQUE(project_id, username)
);

-- Many-to-many: a member can hold any number of roles.
CREATE TABLE IF NOT EXISTS member_roles (
    member_id   INTEGER NOT NULL REFERENCES project_members(id) ON DELETE CASCADE,
    role_id     INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (member_id, role_id)
);

-- Stub table: populated by backup.py when BACKUP_ENABLED = True
CREATE TABLE IF NOT EXISTS backup_log (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp   TEXT    DEFAULT (datetime('now')),
    destination TEXT    NOT NULL,
    status      TEXT    NOT NULL    -- 'ok' | 'error'
);

-- Per-user inbox. "system" messages are generated by the app itself (e.g.
-- project invites); "user" messages would be person-to-person notes if that
-- ever gets built - only the schema/UI need to be ready for it for now.
-- "invite" messages carry a project_id + role_ids in `payload` and are
-- resolved into a real project_members row only on accept.
CREATE TABLE IF NOT EXISTS inbox_messages (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    username    TEXT    NOT NULL,               -- recipient
    kind        TEXT    NOT NULL DEFAULT 'system', -- 'system' | 'user'
    type        TEXT    NOT NULL DEFAULT 'notice', -- 'invite' | 'notice'
    title       TEXT    NOT NULL,
    body        TEXT    DEFAULT '',
    payload     TEXT    DEFAULT '{}',            -- JSON, e.g. {project_id, role_ids}
    status      TEXT    NOT NULL DEFAULT 'unread', -- 'unread'|'read'|'accepted'|'declined'
    created_at  TEXT    DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_inbox_username ON inbox_messages(username);
"""
